AE:
  deterministic: False
  in_size: 64
  norm: "in"
  encoder_type: "resnet50"
  use_actnorm_in_dec: False
  z_dim: 64

Discriminator_Patch:
  in_channels: 3
  ndf: 64
  n_layers: 3
  use_actnorm: True
  spectral_norm: True

Training:
  w_kl: 1e-5
  n_epochs: 60
  lr: 2e-4
  bs: 30
  weight_decay: 0
  workers: 1 # 30
  pretrain: 20
  savename: AE_simple_tasks_instruction_clip_right
  save_path: "run/rlbench"

Data:
  sequence_length: 1
  img_size: 64
  dataset: "RLBench"
  aug: True
  data_path: "datasets/rlbench/processed/simple_tasks_instruction_clip_right.hdf5" # stack_blocks.hdf5" # "datasets/bair/processed_data/" # "INSERT_DATA_PATH_HERE"
  Augmentation:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    prob_hflip: 0.5

Logging:
  entity: "raoxuanzzz"
  project: "cINN_stage2_AE_simple_instruction_clip_right"
  mode: "online" # 'online'

